<?php
$products = array(
    array(
        'img' => 'images/pc/deal-dang-dien-ra/promotions-auto-nuoc-tay-trang-bioderma-danh-cho-da-nhay-cam-500ml_WBG2QcD5K2sybhtV_img_380x380_64adc6_fit_center.png',
        'vn_name' => 'Nước Tẩy Trang Bioderma Dành Cho Da Nhạy Cảm 500ml',
        'en_name' => 'Sensibio H2O',
        'brand' => 'BIODERMA',
        'price' => '382.000 ₫',
        'price_old' => '495.000 ₫',
        'percent' => '23%',
        'gift' => 'Bill fullsize bất kỳ tặng Gel tắm Bioderma Dịu Nhẹ Cho Da Khô 8ml (Hết quà tặng 5K).',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/promotions-auto-sua-rua-mat-cerave-cho-da-thuong-den-kho-473ml_L7bnkFLivULEYqsa_img_380x380_64adc6_fit_center.png',
        'vn_name' => 'Sữa Rửa Mặt CeraVe Cho Da Thường Đến Khô 473ml',
        'en_name' => 'Hydrating Cleanser',
        'brand' => 'CeraVe',
        'price' => '377.000 ₫',
        'price_old' => '380.000 ₫',
        'percent' => '1%',
        'gift' => 'Hóa đơn 399K tặng Túi tote Cerave trị giá 150K (SL có hạn)',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/top_fb_ads_204900013_090622-1663125053_img_380x380_64adc6_fit_center.jpeg',
        'vn_name' => 'Kem Chống Nắng La Roche-Posay Kiểm Soát Dầu SPF50+ 50ml',
        'en_name' => 'Anthelios Anti-Shine Gel-Cream Dry Touch Finish Mattifying Effect SPF50+',
        'brand' => 'LA ROCHE-POSAY',
        'price' => '386.000 ₫',
        'price_old' => '515.000 ₫',
        'percent' => '25%',
        'gift' => 'Tặng: Bông Tẩy Trang Ya Samaya 120 Miếng (Hết quà tặng 15K)',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/top_fb_ads_308100015_220822-1663045473_img_380x380_64adc6_fit_center.jpeg',
        'vn_name' => 'Tẩy Tế Bào Chết Toàn Thân Cocoon Cà Phê Đắk Lắk 200ml',
        'en_name' => 'Dak Lak Coffee Body Polish',
        'brand' => 'Cocoon',
        'price' => '97.000 ₫',
        'price_old' => '115.000 ₫',
        'percent' => '16%',
        'gift' => 'Hóa đơn 199K tặng Son dưỡng Cocoon Dầu Dừa (SL có hạn).',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/promotions-auto-sua-rua-mat-cetaphil-diu-nhe-khong-xa-phong-473ml-moi_nBvSdJeAm89niEf8_img_380x380_64adc6_fit_center.png',
        'vn_name' => 'Sữa Rửa Mặt Cetaphil Dịu Nhẹ Không Xà Phòng 473ml (Mới)',
        'en_name' => 'Gentle Skin Cleanser (New)',
        'brand' => 'CETAPHIL',
        'price' => '315.000 ₫',
        'price_old' => '435.000 ₫',
        'percent' => '28%',
        'gift' => 'Quà tặng: Sữa rửa mặt Cetaphil 59ml(SL có hạn)',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/facebook-dynamic-nuoc-tay-trang-l-oreal-tuoi-mat-cho-da-dau-hon-hop-400ml-1659077090_img_380x380_64adc6_fit_center.jpeg',
        'vn_name' => "Nước Tẩy Trang L'Oreal Tươi Mát Cho Da Dầu, Hỗn Hợp 400ml",
        'en_name' => 'Micellar Water 3-in-1 Refreshing Even For Sensitive Skin',
        'brand' => "L'OREAL",
        'price' => '148.000 ₫',
        'price_old' => '209.000 ₫',
        'percent' => '29%',
        'gift' => 'Quà tặng:  Mặt Nạ Foodaholic ( hết quà tặng 6k)',
    ),

    array(
        'img' => 'images/pc/deal-dang-dien-ra/promotions-auto-nuoc-tay-trang-bioderma-danh-cho-da-nhay-cam-500ml_WBG2QcD5K2sybhtV_img_380x380_64adc6_fit_center.png',
        'vn_name' => 'Nước Tẩy Trang Bioderma Dành Cho Da Nhạy Cảm 500ml',
        'en_name' => 'Sensibio H2O',
        'brand' => 'BIODERMA',
        'price' => '382.000 ₫',
        'price_old' => '495.000 ₫',
        'percent' => '23%',
        'gift' => 'Bill fullsize bất kỳ tặng Gel tắm Bioderma Dịu Nhẹ Cho Da Khô 8ml (Hết quà tặng 5K).',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/promotions-auto-sua-rua-mat-cerave-cho-da-thuong-den-kho-473ml_L7bnkFLivULEYqsa_img_380x380_64adc6_fit_center.png',
        'vn_name' => 'Sữa Rửa Mặt CeraVe Cho Da Thường Đến Khô 473ml',
        'en_name' => 'Hydrating Cleanser',
        'brand' => 'CeraVe',
        'price' => '377.000 ₫',
        'price_old' => '380.000 ₫',
        'percent' => '1%',
        'gift' => 'Hóa đơn 399K tặng Túi tote Cerave trị giá 150K (SL có hạn)',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/top_fb_ads_204900013_090622-1663125053_img_380x380_64adc6_fit_center.jpeg',
        'vn_name' => 'Kem Chống Nắng La Roche-Posay Kiểm Soát Dầu SPF50+ 50ml',
        'en_name' => 'Anthelios Anti-Shine Gel-Cream Dry Touch Finish Mattifying Effect SPF50+',
        'brand' => 'LA ROCHE-POSAY',
        'price' => '386.000 ₫',
        'price_old' => '515.000 ₫',
        'percent' => '25%',
        'gift' => 'Tặng: Bông Tẩy Trang Ya Samaya 120 Miếng (Hết quà tặng 15K)',
    ),
    array(
        'img' => 'images/pc/deal-dang-dien-ra/top_fb_ads_308100015_220822-1663045473_img_380x380_64adc6_fit_center.jpeg',
        'vn_name' => 'Tẩy Tế Bào Chết Toàn Thân Cocoon Cà Phê Đắk Lắk 200ml',
        'en_name' => 'Dak Lak Coffee Body Polish',
        'brand' => 'Cocoon',
        'price' => '97.000 ₫',
        'price_old' => '115.000 ₫',
        'percent' => '16%',
        'gift' => 'Hóa đơn 199K tặng Son dưỡng Cocoon Dầu Dừa (SL có hạn).',
    ),




    array(
        'img' => '',
        'vn_name' => '',
        'en_name' => '',
        'brand' => '',
        'price' => '',
        'price_old' => '',
        'percent' => '',
        'gift' => '',
    ),
);
?>